### ISSUE TITLE
We need to find an actor by email to be able to do the login

### ISSUE THREAD

**Issue by tatacsd** [tatacsd/Product-Unit-Cost-Application-Project#56]
![image](https://user-images.githubusercontent.com/29147847/161003390-50fd4372-f497-49d1-bc82-8f0ef9966514.png)
we just have get by id
![image](https://user-images.githubusercontent.com/29147847/161004650-58d4df74-ee4d-4670-96cb-786a281fa3e0.png)

**Comment by tatacsd** [comment]
Hey @Andrew-shanan  we need this endpoint to be able to create the login

**Comment by Andrew-shanan** [comment]
it is solved
